spring.application.name=payment-service

server.port=8085

spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
internal.api-key=${INTERNAL_API_KEY:dev-internal-key}