spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommance_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin

internal.api-key=${INTERNAL_API_KEY:dev-internal-key}
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}