spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html

jwt.jwk-set-uri=http://localhost:8081/.well-known/jwks.json
product.service.url=http://localhost:8082
internal.api-key=${INTERNAL_API_KEY:dev-internal-key}
