spring.application.name=product-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommance_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html

internal.api-key=${INTERNAL_API_KEY:dev-internal-key}

jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}